version: '3.8'

name: tradings

volumes:
  tradings_postgresql_volume:
  tradings_redis_volume:
  tradings_ssh_volume:

services:

  redis:
    command: redis-server --save 60 1
    container_name: tradings_redis
    expose:
      - 6379
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 60s
      retries: 5
    hostname: tradings_redis_host
    image: redis:7.2.1-alpine3.18
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    restart: on-failure
    volumes:
      - tradings_redis_volume:/data/

  postgresql:
    container_name: tradings_postgresql
    env_file:
      - ../app/src/config/.env
    expose:
      - 5432
    hostname: tradings_postgresql_host
    image: postgres:15-alpine3.18
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    restart: on-failure
    volumes:
      - tradings_postgresql_volume:/var/lib/postgresql/data/

  pg_admin:
    container_name: tradings_pg_admin
    depends_on:
      - postgresql
    env_file:
      - ../app/src/config/.env
    hostname: tradings_pg_admin_host
    image: dpage/pgadmin4
    restart: on-failure

  backend:
    build:
      context: ../app
      dockerfile: Dockerfile
    command: sh -c "
      alembic upgrade head &
      python src/main.py &
      celery -A src.celery_app.celery_app:celery_app worker --loglevel=INFO &
      celery -A src.celery_app.celery_app:celery_app beat --loglevel=INFO &
      celery -A src.celery_app.celery_app:celery_app flower --basic_auth=${CELERY_FLOWER_ADMIN_USERNAME}:${CELERY_FLOWER_ADMIN_PASSWORD} --loglevel=INFO"
    container_name: tradings_backend
    depends_on:
      - redis
      - postgresql
    env_file:
      - ../app/src/config/.env
    hostname: tradings_backend_host
    restart: on-failure
    volumes:
      - ../app:/app

  gateway:
    container_name: tradings_gateway
    depends_on:
      - backend
      - pg_admin
    image: nginx:1.21.3-alpine
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    ports:
      - "5050:5050"  # pg_admin
      - "5555:5555"  # celery-flower
      - "8000:8000"  # backend
    restart: on-failure
    volumes:
      - ../gateway/nginx.conf:/etc/nginx/conf.d/default.conf
