"""empty message

Revision ID: a9a43c24f34c
Revises: 
Create Date: 2024-04-12 06:18:19.025963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a43c24f34c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_product_category',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='название'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_used_pass_reset_token',
    sa.Column('exp_date', sa.DateTime(timezone=True), nullable=False, comment='дата и время окончания срока жизни'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('token', sa.String(length=256), nullable=False, comment='токен'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('email', sa.String(length=190), nullable=False, comment='email'),
    sa.Column('email_is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Статус подтвержденной почты'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='статус активного'),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='статус администратора'),
    sa.Column('is_salesman', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='статус продавца'),
    sa.Column('hashed_password', sa.String(length=256), nullable=True, comment='хэш пароля'),
    sa.Column('name_first', sa.String(length=25), nullable=False, comment='имя'),
    sa.Column('name_last', sa.String(length=25), nullable=False, comment='фамилия'),
    sa.Column('phone', sa.String(length=20), server_default=sa.text('NULL'), nullable=True, comment='номер телефона'),
    sa.Column('phone_is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Статус подтвержденного номера телефона'),
    sa.Column('registration_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата и время регистрации'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('table_product',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('description', sa.String(length=200), nullable=False, comment='описание'),
    sa.Column('in_stock', sa.Integer(), nullable=False, comment='в наличии'),
    sa.Column('price', sa.Integer(), nullable=False, comment='цена'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='название'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='id категории товаров'),
    sa.Column('salesman_id', sa.Integer(), nullable=False, comment='id продавца'),
    sa.ForeignKeyConstraint(['category_id'], ['table_product_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesman_id'], ['table_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_user_salesman',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя-продавца'),
    sa.Column('company_name', sa.String(length=50), nullable=False, comment='название компании'),
    sa.Column('description', sa.String(length=200), server_default=sa.text('NULL'), nullable=True, comment='описание компании'),
    sa.Column('image', sa.String(length=200), server_default=sa.text('NULL'), nullable=True, comment='изображение компании'),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='статус верификации'),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), server_default=sa.text('CAST(0.0 AS DECIMAL(3, 2))'), nullable=False, comment='рейтинг'),
    sa.ForeignKeyConstraint(['user_id'], ['table_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_user_salesman')
    op.drop_table('table_product')
    op.drop_table('table_user')
    op.drop_table('table_used_pass_reset_token')
    op.drop_table('table_product_category')
    # ### end Alembic commands ###
