"""empty message

Revision ID: 6c89b907f981
Revises: a9a43c24f34c
Create Date: 2024-04-12 10:11:28.896896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c89b907f981'
down_revision: Union[str, None] = 'a9a43c24f34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_feedback',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('contacts', sa.String(length=50), nullable=False, comment='телефон или телеграм'),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата и время отправки'),
    sa.Column('data_process_approve', sa.Boolean(), nullable=False, comment='согласие на обработку персональных данных'),
    sa.Column('email', sa.String(length=190), nullable=False, comment='email'),
    sa.Column('is_accepted', sa.Boolean(), nullable=False, comment='статус отправки в поддержку'),
    sa.Column('message', sa.String(length=200), nullable=False, comment='сообщение'),
    sa.Column('username', sa.String(length=25), nullable=False, comment='имя'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_feedback')
    # ### end Alembic commands ###
